# Generated by Django 2.2.8 on 2019-12-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190628_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pic',
            field=models.ImageField(default='IMG', upload_to='images/'),
        ),
    ]
